### ISSUE TITLE
Additional things to test

### ISSUE THREAD

**Issue by yoshrote** [slinkp/dj_related_signals#2]
- Do post-save hooks follow the same behavior as pre-save hooks?
- We have tests for direct assignment of 1toM relationships but what about when calling `parent_obj.add(child)`? This becomes more important with my next point...
- All of the tests seem to assume that you save a child object and then attach it to the parent.  What changes in behavior happen when an non-persisted child object is added to the parent object and then `parent.save()` is called. Also does the behavior differ when done via direct assignment vs calling `parent.add()`?

**Comment by slinkp** [comment]
Will add tests for post-save.
Will add tests for parent.add(child).
Will check unsaved objects with `add()`.

You can't do direct assignment at all on an unsaved 1-to-1 child.
Example (same behavior on 1.8 and 1.9):
```pycon
>>> customer = models.Customer(name='1to1 forward test', company=self.company)
>>> extra = models.CustomerExtraJunk()
>>> extra.save()

ValueError: save() prohibited to prevent data loss due to unsaved related object 'customer'.
```

Same is true on forward many-to-one relationships:
```pycon
>>> customer = models.Customer(name='bob')
>>> company = models.Company(name='x')
>>> customer.company = company
>>> customer.save()

ValueError: save() prohibited to prevent data loss due to unsaved related object 'company'.
```
Likewise you can't assign a list of unsaved children to a direct m2m field on a saved parent:

```pycon
>>> customer.save()
>>> cat1 = models.CustomerCategory(name='cat1')
>>> customer.categories_direct = [cat1]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/paul/hacking/dj_related_experiment_2019/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1275, in __set__
    manager.add(*value)
  File "/Users/paul/hacking/dj_related_experiment_2019/lib/python2.7/site-packages/django/db/models/fields/related.py", line 985, in add
    self._add_items(self.source_field_name, self.target_field_name, *objs)
  File "/Users/paul/hacking/dj_related_experiment_2019/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1068, in _add_items
    (obj, self.instance._state.db, obj._state.db)
ValueError: Cannot add "<CustomerCategory: CustomerCategory object>": instance is on database "default", value is on database "None"
>>> cat1.save()
>>> customer.categories_direct = [cat1]
```

Reverse direct assignment on a 1to1 field is a bit interesting, will add a test around that.

**Comment by slinkp** [comment]
@yoshrote  i think I've done all these now. Anything else I'm missing?
